spring:
  application:
    name: serve-admin
  zipkin:
    base-url: http://localhost:9604

server:
  port: 9605

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:9601/eureka/

# admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
