spring:
  application:
    name: serve-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9602

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:9601/eureka/

zuul:
  #strip-prefix: false
  # 排除的服务
  #ignored-services: serve-sys
  routes:
    # 路由名称，随意
    serve-sys:
      # 路由地址
      path: /api/sys/**
      # 该路由地址对应的服务名称
      serviceId: serve-sys
    serve-auth:
      path: /api/auth/**
      serviceId: serve-auth

# 配置 Zuul 管理端点 /actuator/routes, /actuator/filters 可访问
management:
  endpoints:
    web:
      exposure:
        include: '*'

