spring:
  application:
    name: serve-sys
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9701

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:9601/eureka/

